version: '3'

services:

  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: web-stream-vue_web
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  app:
    image: web-stream-app
    build: ./app
    ports:
      - "8000:8000"
